//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public long ExpenseId { get; set; }
        public Nullable<long> ManufacturerId { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<long> Value { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
