//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.Expenses = new HashSet<Expens>();
            this.Products = new HashSet<Product>();
        }
    
        public long ManufacturerId { get; set; }
        public string ManufacturerName { get; set; }
    
        public virtual ICollection<Expens> Expenses { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
