//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductTaxes = new HashSet<ProductTax>();
        }
    
        public long ProductId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductTax> ProductTaxes { get; set; }
    }
}
