//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long SaleId { get; set; }
        public Nullable<long> StoreId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> Sum { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
